### ISSUE TITLE
Issues with references to profiles and extensions from VS pages

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/ballot#42] opened 2018-03-28 18:55 UTC
The links go back to logical models and profiles, not "just" profiles and extensions. Moreover, the link text is the same and the reader can only distinguish the profile from the model by hovering over the link text.

![image](https://user-images.githubusercontent.com/18464954/38050056-760b7238-328f-11e8-9568-2aa69a65469a.png)

**Comment by cmoesel** [comment] 2018-03-28 18:59
This is a duplicate of #38.

**Closed as completed by cmoesel** 2018-03-28 18:59 UTC
Labels: duplicate
